var goreyArray = [
	"Agatha pedalled to the neighbouring village for help. ",
	"Agatha taught Adolphus to dance the one-step. ",
	"Agatha finished knitting a scarf for Augustus. ",
	"Amanda wrote a note to Augustus. ",
	"Amanda found several unfolded napkins on a back shelf. ",
	"Andrew recieved a postcard from Amaryllis. ",
	"Andrew came across a horrid secret in Adela's diary. ",
	"Adela could not find her way out of the woods. ",
	"Adela became disoriented at Alaric's funeral. ",
	"Adela flung Angela's baby from an upstairs window. ",
	"Angus concealed a lemon behind a cushion. ",
	"Angus lost a shoe not far from the folly. ",
	"Angus inherited the grandfather clock from Aunt Ada. ",
	"Alfred returned from Novaya Zemlya. ",
	"Albert left for Peru. ",
	"Ambrose took an overdose of sarsaparilla. ",
	"Alethea vanished from a picnic. ",
	"Arthur's outdoor garments turned up in a guestroom closet. ",
	"A disguised person came to one of the side doors. ",
	"A mysterious urn appeared in the grounds. "
];